version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0.2
    steps:
      - checkout
      - run: gradle build
      - run: gradle test

workflows:
  build_and_test:
    jobs:
      - build
      - test