/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myDemoApp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;
class AppTest {

    @Test
    public void testValidList() {
        ArrayList list = new ArrayList<>(Arrays.asList(1,2,3,4,5,6,7,8));
        Integer number1 = 2, number2 = 9;
        assertTrue(App.hasBetweenIntegers(list, number1, number2));
    }

    @Test
    public void testEmptyList() {
        ArrayList list = new ArrayList<>();
        Integer number1 = 2, number2 = 3;
        assertFalse(App.hasBetweenIntegers(list, number1, number2));
    }

    @Test
    public void testValidListNoSuchElement() {
        ArrayList list = new ArrayList<>(Arrays.asList(1,2,3,4,5,6,7,8));
        Integer number1 = 9, number2 = 16;
        assertFalse(App.hasBetweenIntegers(list, number1, number2));
    }

    @Test
    public void testInvalidNumbers() {
        ArrayList list = new ArrayList<>(Arrays.asList(1,2,3,4,5,6,7,8));
        Integer number1 = 9, number2 = 6;
        assertFalse(App.hasBetweenIntegers(list, number1, number2));
    }

    @Test
    public void testNullList() {
        assertFalse(App.hasBetweenIntegers(null, 0, 0));
    }
}
