/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myDemoApp;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static boolean hasBetweenIntegers(ArrayList<Integer> list, Integer number1, Integer number2) {
        
        //list cannot be null
        if(list == null)
            return false;
        
        //list cannot be empty
        if(list.size() == 0)
            return false;

        //num1 cannot be greater than num2
        if(number1 > number2)
            return false;

        for (Integer elt : list) {
            if(elt >= number1 && elt <= number2)
                return true;  
        }

        //no such element
        return false;
    }
}
