/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myDemoApp;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import static spark.Spark.*;
import spark.ModelAndView;
import spark.template.mustache.MustacheTemplateEngine;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        get("/", (req, res) -> "Welcome to my first Web Application!!!");

        get("/compute", 
            (req, res) -> {
                Map<String, String> map = new HashMap<String, String>();
                map.put("result", "Not computed yet");
                return new ModelAndView(map, "compute.mustache");
            },
            new MustacheTemplateEngine()
        );

        post("/compute", 
             (req, res) -> {
                System.out.println(req.queryParams("input1"));
                System.out.println(req.queryParams("input2"));
    
                String input1 = req.queryParams("input1");
                java.util.Scanner sc1 = new java.util.Scanner(input1);
                sc1.useDelimiter("[;\r\n]+");
                java.util.ArrayList<Integer> inputList = new java.util.ArrayList<>();
                while (sc1.hasNext())
                {
                int value = Integer.parseInt(sc1.next().replaceAll("\\s",""));
                inputList.add(value);
                }
                sc1.close();
                System.out.println(inputList);
    
    
                String input2 = req.queryParams("input2").replaceAll("\\s","");
                int input2AsInt = Integer.parseInt(input2);

                String input3 = req.queryParams("input3").replaceAll("\\s","");
                int input3AsInt = Integer.parseInt(input3);
    
                boolean result = App.hasBetweenIntegers(inputList, input2AsInt, input3AsInt);
    
                Map<String, Boolean> map = new HashMap<String, Boolean>();
                map.put("result", result);
                return new ModelAndView(map, "compute.mustache");
            },
            new MustacheTemplateEngine());
  
    }

    public static boolean hasBetweenIntegers(ArrayList<Integer> list, Integer number1, Integer number2) {
        
        //list cannot be null
        if(list == null)
            return false;
        
        //list cannot be empty
        if(list.size() == 0)
            return false;

        //num1 cannot be greater than num2
        if(number1 > number2)
            return false;

        for (Integer elt : list) {
            if(elt >= number1 && elt <= number2)
                return true;  
        }

        //no such element
        return false;
    }
}
